# Generated by Django 5.2.4 on 2025-08-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="strategy",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="strategy",
            name="asset",
            field=models.ForeignKey(
                default="",
                help_text="Asset sur lequel appliquer la stratégie",
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_app.asset",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="strategy",
            name="broker",
            field=models.ForeignKey(
                help_text="Broker pour exécuter les ordres",
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_app.brokercredentials",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="strategy",
            unique_together={("user", "asset", "name")},
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(fields=["asset"], name="trading_app_asset_i_1a38d6_idx"),
        ),
    ]
