# Generated by Django 4.2.7 on 2025-08-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pendingorder",
            name="trading_app_all_ass_1855b9_idx",
        ),
        migrations.RemoveField(
            model_name="pendingorder",
            name="all_asset",
        ),
        migrations.AddField(
            model_name="pendingorder",
            name="asset_tradable",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_app.assettradable",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="pendingorder",
            index=models.Index(
                fields=["asset_tradable", "status"],
                name="trading_app_asset_t_71c6fb_idx",
            ),
        ),
    ]
