# Generated by Django 5.2.4 on 2025-08-04 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="asset",
        ),
        migrations.AddField(
            model_name="trade",
            name="asset_tradable",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_app.assettradable",
            ),
            preserve_default=False,
        ),
    ]
