# Generated by Django 5.2.4 on 2025-07-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokercredentials",
            name="environment",
            field=models.CharField(
                choices=[("live", "Live Trading"), ("simulation", "Simulation/Demo")],
                default="simulation",
                help_text="Environnement de trading (Live ou Simulation)",
                max_length=20,
            ),
        ),
    ]
