# Generated by Django 5.2.4 on 2025-07-24 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broker_type",
                    models.CharField(
                        choices=[("saxo", "Saxo Bank"), ("binance", "Binance")],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom pour identifier cette configuration",
                        max_length=100,
                    ),
                ),
                (
                    "saxo_client_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "saxo_client_secret",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("saxo_redirect_uri", models.URLField(blank=True, null=True)),
                ("saxo_access_token", models.TextField(blank=True, null=True)),
                ("saxo_refresh_token", models.TextField(blank=True, null=True)),
                ("saxo_token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "binance_api_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "binance_api_secret",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("binance_testnet", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "broker_type", "name")},
            },
        ),
    ]
