# Generated by Django 4.2.7 on 2025-08-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading_app",
            "0002_remove_pendingorder_trading_app_all_ass_1855b9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='assettradable',
            name='quantity',
            field=models.DecimalField(
                max_digits=15,
                decimal_places=6,
                default=0,
                help_text="Quantité totale des positions ouvertes pour cet asset"
            ),
        ),
    ]
