# Generated by Django 5.2.4 on 2025-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0002_brokercredentials_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("saxo", "Saxo Bank"),
                            ("binance", "Binance"),
                            ("yahoo", "Yahoo Finance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("asset_type", models.CharField(max_length=50)),
                ("market", models.CharField(max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("exchange", models.CharField(blank=True, max_length=100)),
                ("is_tradable", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("saxo_uic", models.IntegerField(blank=True, null=True)),
                ("saxo_exchange_id", models.CharField(blank=True, max_length=20)),
                ("saxo_country_code", models.CharField(blank=True, max_length=10)),
                ("binance_base_asset", models.CharField(blank=True, max_length=20)),
                ("binance_quote_asset", models.CharField(blank=True, max_length=20)),
                ("binance_status", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["platform", "asset_type"],
                        name="trading_app_platfor_13a3b5_idx",
                    ),
                    models.Index(
                        fields=["symbol"], name="trading_app_symbol_424f8e_idx"
                    ),
                    models.Index(fields=["name"], name="trading_app_name_574d09_idx"),
                ],
                "unique_together": {("symbol", "platform")},
            },
        ),
    ]
