# Generated by Django 5.2.4 on 2025-08-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0002_alter_strategy_unique_together_strategy_asset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="asset_tradable",
        ),
        migrations.RemoveField(
            model_name="trade",
            name="asset_tradable",
        ),
        migrations.AddField(
            model_name="position",
            name="asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_app.asset",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trade",
            name="asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_app.asset",
            ),
            preserve_default=False,
        ),
    ]
