# Generated by Django 5.2.4 on 2025-08-05 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0002_remove_trade_asset_trade_asset_tradable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=100, unique=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("STOP", "Stop"),
                            ("STOP_LIMIT", "Stop Limit"),
                            ("OCO", "One-Cancels-Other"),
                        ],
                        default="MARKET",
                        max_length=20,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Achat"), ("SELL", "Vente")], max_length=4
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("WORKING", "En cours"),
                            ("PARTIALLY_FILLED", "Partiellement exécuté"),
                            ("FILLED", "Exécuté"),
                            ("CANCELLED", "Annulé"),
                            ("REJECTED", "Rejeté"),
                            ("EXPIRED", "Expiré"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "original_quantity",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "executed_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("broker_data", models.JSONField(default=dict)),
                (
                    "all_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading_app.allassets",
                    ),
                ),
                (
                    "broker_credentials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading_app.brokercredentials",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="trading_app_user_id_26b008_idx"
                    ),
                    models.Index(
                        fields=["all_asset", "status"],
                        name="trading_app_all_ass_1855b9_idx",
                    ),
                    models.Index(
                        fields=["order_id"], name="trading_app_order_i_d17397_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="trading_app_created_395569_idx"
                    ),
                ],
            },
        ),
    ]
