# Generated by Django 5.2.4 on 2025-08-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0003_allassets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assettradable",
            name="asset",
        ),
        migrations.AddField(
            model_name="assettradable",
            name="all_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tradable_versions",
                to="trading_app.allassets",
            ),
        ),
        migrations.AddField(
            model_name="assettradable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
