# Generated by Django 4.2.7 on 2025-08-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0003_auto_20250814_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="portfolio_quantity",
            field=models.DecimalField(
                decimal_places=6,
                default=-1,
                help_text="Quantité totale en portefeuille pour cet asset (pré-calculée)",
                max_digits=15,
            ),
        ),
    ]
