# Generated by Django 4.2.7 on 2025-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0004_strategy_portfolio_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="target_max_quantity",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Quantité maximale cible à maintenir en portefeuille",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="target_min_quantity",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Quantité minimale cible à maintenir en portefeuille",
                max_digits=15,
            ),
        ),
    ]
