# Generated by Django 5.2.4 on 2025-08-03 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading_app",
            "0004_remove_assettradable_asset_assettradable_all_asset_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assettradable",
            name="all_asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tradable_versions",
                to="trading_app.allassets",
            ),
        ),
    ]
