# Generated by Django 5.2.4 on 2025-08-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0005_strategy_target_max_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokercredentials",
            name="auto_refresh_enabled",
            field=models.BooleanField(default=True, verbose_name="Auto-refresh activé"),
        ),
        migrations.AddField(
            model_name="brokercredentials",
            name="auto_refresh_frequency",
            field=models.IntegerField(
                default=45,
                help_text="Fréquence en minutes (15-55 min)",
                verbose_name="Fréquence auto-refresh (minutes)",
            ),
        ),
        migrations.CreateModel(
            name="TokenRefreshHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refresh_attempted_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("new_access_token", models.TextField(blank=True, null=True)),
                ("new_refresh_token", models.TextField(blank=True, null=True)),
                ("expires_in_seconds", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=5)),
                (
                    "broker_credentials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_refresh_history",
                        to="trading_app.brokercredentials",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique Refresh Token",
                "verbose_name_plural": "Historiques Refresh Token",
                "ordering": ["-refresh_attempted_at"],
            },
        ),
    ]
