# Generated by Django 5.2.4 on 2025-08-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0005_alter_assettradable_all_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="allassets",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="allassets",
            name="market_cap",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="allassets",
            name="sector",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
