# Generated by Django 5.2.4 on 2025-08-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0006_brokercredentials_auto_refresh_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokercredentials",
            name="saxo_environment",
            field=models.CharField(
                choices=[("live", "Live"), ("simulation", "Simulation")],
                default="simulation",
                max_length=20,
                verbose_name="Environnement Saxo",
            ),
        ),
    ]
