# Generated by Django 5.2.4 on 2025-08-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0006_allassets_industry_allassets_market_cap_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allassets",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="allassets",
            name="market_cap",
        ),
        migrations.RemoveField(
            model_name="allassets",
            name="sector",
        ),
    ]
