# Generated by Django 5.2.4 on 2025-08-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0007_remove_allassets_industry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="all_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enriched_assets",
                to="trading_app.allassets",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="symbol_clean",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
