# Generated by Django 4.2.7 on 2025-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0007_brokercredentials_saxo_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="broker_position_id",
            field=models.CharField(
                blank=True,
                help_text="ID unique de la position selon le broker",
                max_length=100,
                null=True,
            ),
        ),
    ]
