# Generated by Django 4.2.7 on 2025-08-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0008_position_broker_position_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="broker_position_id",
        ),
    ]
