# Generated by Django 4.2.7 on 2025-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0009_remove_position_broker_position_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="broker_position_id",
            field=models.CharField(
                default=1,
                help_text="ID unique de la position chez le broker",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
