# Generated by Django 4.2.7 on 2025-08-18 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trading_app", "0010_position_broker_position_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("execution_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Succès"),
                            ("PARTIAL", "Partiel"),
                            ("FAILED", "Échec"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Résumé des actions effectuées"),
                ),
                ("api_responses", models.TextField(help_text="Réponses des APIs")),
                (
                    "errors",
                    models.TextField(blank=True, help_text="Erreurs rencontrées"),
                ),
                ("execution_duration", models.DurationField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-execution_time"],
            },
        ),
        migrations.CreateModel(
            name="AutomationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Activer/désactiver l'automatisation"
                    ),
                ),
                (
                    "frequency_minutes",
                    models.IntegerField(default=30, help_text="Fréquence en minutes"),
                ),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True, help_text="Dernière exécution", null=True
                    ),
                ),
                (
                    "next_execution",
                    models.DateTimeField(
                        blank=True,
                        help_text="Prochaine exécution programmée",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user",)},
            },
        ),
    ]
