# Generated by Django 4.2.7 on 2025-08-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_app", "0011_automationexecutionlog_automationconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="automationconfig",
            name="auto_refresh_tokens",
            field=models.BooleanField(
                default=True, help_text="Activer le refresh automatique des tokens"
            ),
        ),
    ]
