# Generated by Django 4.2.7 on 2025-08-13 11:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("is_alcoholic", models.BooleanField(default=True)),
                ("popularity", models.PositiveIntegerField(default=0)),
                ("preparation_time_min", models.PositiveIntegerField(default=5)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cocktails/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cocktails",
                        to="cocktails_app.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("definition", models.TextField(blank=True)),
                ("quantity_text", models.TextField(blank=True)),
                ("cost_text", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "default_unit",
                    models.CharField(
                        choices=[
                            ("ml", "ml"),
                            ("cl", "cl"),
                            ("l", "l"),
                            ("g", "g"),
                            ("pcs", "pièces"),
                        ],
                        default="ml",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_alcohol", models.BooleanField(default=False)),
                ("buy_link", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cart", "Panier"),
                            ("pending", "En attente"),
                            ("paid", "Payée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="cart",
                        max_length=20,
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=120)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("customer_phone", models.CharField(blank=True, max_length=40)),
                ("delivery_address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="% de réduction", max_digits=5
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cocktails_app.cocktail",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cocktails_app.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cocktails_app.promotion",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cocktails_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FormulaCocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servings", models.PositiveIntegerField(default=1)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cocktails_app.cocktail",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formula_items",
                        to="cocktails_app.formula",
                    ),
                ),
            ],
            options={
                "unique_together": {("formula", "cocktail")},
            },
        ),
        migrations.AddField(
            model_name="formula",
            name="cocktails",
            field=models.ManyToManyField(
                related_name="formulas",
                through="cocktails_app.FormulaCocktail",
                to="cocktails_app.cocktail",
            ),
        ),
        migrations.CreateModel(
            name="CocktailIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("unit", models.CharField(default="ml", max_length=10)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_items",
                        to="cocktails_app.cocktail",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_in",
                        to="cocktails_app.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("cocktail", "ingredient")},
            },
        ),
    ]
