# Generated by Django 5.2.4 on 2025-08-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cocktails_app", "0002_ingredient_buy_link_alter_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("definition", models.TextField(blank=True)),
                ("quantity_text", models.TextField(blank=True)),
                ("cost_text", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormulaCocktail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servings", models.PositiveIntegerField(default=1)),
                (
                    "cocktail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cocktails_app.cocktail",
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formula_items",
                        to="cocktails_app.formula",
                    ),
                ),
            ],
            options={
                "unique_together": {("formula", "cocktail")},
            },
        ),
        migrations.AddField(
            model_name="formula",
            name="cocktails",
            field=models.ManyToManyField(
                related_name="formulas",
                through="cocktails_app.FormulaCocktail",
                to="cocktails_app.cocktail",
            ),
        ),
    ]
